<template>
  <section class="content" :class="{ja: displayLanguage === 'ja'}">

    <Breadcrumb 
      :title="title"
    />

    <div 
      class="japanese-available content-top-full" 
      v-if="(userLanguage === 'ja' || isDev) && content.ja && content.en"
    >
      <template v-if="displayLanguage !== 'ja'">
        <img src="~/assets/japanFlag.svg" class="flag-icon" />
        <span>日本語版もあります。</span>
        <span class="button invert" @click="setLanguage('ja')">切り替える</span>
      </template>
      <template v-else>
        <span>日本語版を表示しています。</span>
        <span class="button invert" @click="setLanguage('en')">英語に戻る</span>
      </template>
    </div>


    <h1>{{ title }}</h1>

    <PostDetails
      class="details"
      :category="category"
      :mapPosition="mapPosition"
      :city="city"
      :date="date"
    />

    <article
      v-lazy-container="{ selector: 'img'}"
      class="markdown"
      ref="postcontent"
      v-html="formatMarkdown(
        $md.render(
          contentToDisplay
        )
      )"
    ></article>

    <RelatedArticles :city="city" :current="slug" />

    <Footer/>

  </section>
</template>

<script>
import axios from 'axios'
import Footer from '~/components/Footer'
import PostDetails from '~/components/PostDetails'
import RelatedArticles from '~/components/RelatedArticles'
import Breadcrumb from '~/components/Breadcrumb'
import { capitalize } from '~/assets/commonFunctions.js'

export default {
  head() {
    return {
      title: this.capitalize(this.title),
      meta: [
        { property: 'og:title', content: this.capitalize(this.title) },
        { hid: `og:type`, property: 'og:type', content: 'article' },
        { hid: `og:description`, property: 'og:description', content: this.description },
        { property: 'description', content: this.description, hid: `description` },
        { property: 'og:url', content: `https://www.travelingcircusofurbanism.com${ this.rawPath }` },
        { hid: `og:image`, property: 'og:image', content: `https://www.travelingcircusofurbanism.com${ this.image ? this.image.replace(/\s/g, '%20') : '' }` },
      ],
      // script: [
      //   { src: '/assets/pinit.js', defer: true, async: true, "data-pin-hover":"true", "data-pin-round":"true" }
      // ]
    }
  },
  
  components: { Footer, RelatedArticles, PostDetails, Breadcrumb, },

  asyncData ({ route, redirect, error, env, store }) {
    const slug = route.path.replace(/\/$/, '')
      .replace('%20', ' ')

    const path = '/posts' + slug + '/'
    const rawPath = '/posts' + route.path.replace(/\/$/, '') + '/'

    let city = route.path.substring(1)
    city = city.substring(0, city.indexOf('/'))
      .replace('%20', ' ')

    const autoGeneratedData = store.state.allPosts
      .find(p => city === p.city && slug.indexOf(p.slug) !== -1)
    if (!autoGeneratedData) {
      console.log('Error: Unable to find generated data for ' + path)
      return error({ statusCode: 404, message: 'Page not found.' })
    }

    return {
      path,
      rawPath,
      slug,
      city,
      ...autoGeneratedData,
      mapPosition: autoGeneratedData.mapPosition ? Array.concat([], autoGeneratedData.mapPosition) : [],
    }
  },

  data () {
    return {
      displayLanguage: 'en',
      content: {
        en: null,
        ja: null
      }
    }
  },

  computed: {
    isDev () { return this.$store.state.isDev },
    isMobile () { return this.$store.state.isMobile },
    userLanguage () { return this.$store.state.language },
    contentToDisplay () {
      let contentToDisplay = this.content[this.displayLanguage] || this.content.en || this.content.ja || ''
      // remove title
      contentToDisplay = contentToDisplay.substring(contentToDisplay.indexOf('#'))
      return contentToDisplay.substring(contentToDisplay.indexOf('\n'))
    }
  },

  async created () {
    if (!process.browser) return
    const axiosConfig = {
      validateStatus: status => true,
    }
  
    const contentPromises = []
    if (this.languages.en)
      contentPromises.push(
        axios.get(this.path + 'content.md', axiosConfig)
          .then(response => {
            this.$set(this.content, 'en', response.data)
          })
          .catch(e => console.log(e))
      )
    if (this.languages.ja)
      contentPromises.push(
        axios.get(this.path + 'ja.md', axiosConfig)
          .then(response => {
            this.$set(this.content, 'ja', response.data)
          })
          .catch(e => console.log(e))
      )
    await Promise.all(contentPromises)

    if (!(this.content.en || this.content.ja)) return this.$router.push('/')
    if (this.content.en) this.setLanguage('en')
    else this.setLanguage('ja')
  },

  mounted () {
    this.displayLanguage = this.content.en ? 'en' : 'ja'
    this.$store.commit('setView', this.mapPosition)
    this.$store.commit('setCity', this.city)
    this.$store.commit('setPan', false)
    this.$store.commit('setHighlight', this.mapPosition)
  },

  beforeDestroy () {
    this.$store.commit('setHighlight')
  },

  methods: {
    capitalize,

    doubleHighlight (location) {
      this.$store.commit('setHighlight', location)
    },

    unDoubleHighlight () {
      this.$store.commit('setHighlight')
    },

    setLanguage (language) {
      this.displayLanguage = language
      this.$nextTick(this.addHighlightForLinks)
    },

    formatMarkdown (baseMD) {
      if (!baseMD) return ''
      let newMD = baseMD
      // fix internal images
      const localImageElementRegex = /<img src=\"(?!http|www\.)\/?(?:(?:[^\/,"]+\/)*)(.+)\.(jpe?g|png|gif|webm|svg)" ?(?:alt(?:="(.*)")?)?/gim
      let matches = localImageElementRegex.exec(baseMD)
      while (matches != null) {
        const srcImagePath = encodeURI(`${ this.path }resized/${ matches[1] }.${ matches[2] }`)
        const fullSizeImagePath = encodeURI(`https://www.travelingcircusofurbanism.com${ this.path }full/${ matches[1] }.${ matches[2] }`)
        const description = (matches[3] || '').replace('"', '\'')
        const postPath = encodeURI(`https://www.travelingcircusofurbanism.com${ this.url }`)
        const imageTagToSwapIn = `
          <img 
            data-src="${ srcImagePath }"
            ${ description ? 
              `alt="${ description }"
              data-pin-description="${ description }"`
              : ''
            }
            data-pin-url="${ postPath }"
            data-pin-media="${ fullSizeImagePath }"`
        newMD = newMD.replace(matches[0], imageTagToSwapIn)
        matches = localImageElementRegex.exec(baseMD)
      }
      // fix external images
      const externalImageElementRegex = /<img src="((?:http|www\.).*(?:jpe?g|png|gif|webm|svg))" ?(?:alt(?:="(.*)")?)?/gim
      matches = externalImageElementRegex.exec(baseMD)
      while (matches != null) {
        const srcImagePath = matches[1]
        const description = (matches[2] || '').replace('"', '\'')
        const postPath = encodeURI(`https://www.travelingcircusofurbanism.com${ this.url }`)
        const imageTagToSwapIn = `
          <img 
            data-src="${ srcImagePath }"
            ${ description ? 
              `alt="${ description }"
              data-pin-description="${ description }"`
              : ''
            }
            data-pin-url="${ postPath }"
            data-pin-media="${ srcImagePath }"`
        console.log(imageTagToSwapIn)
        newMD = newMD.replace(matches[0], imageTagToSwapIn)
        matches = externalImageElementRegex.exec(baseMD)
      }

      // make external links open in new tab
      newMD = newMD.replace(/<a href="([^"]*)">/g, 
        (match, url) => {
          const externalAttributes = url.indexOf('travelingcircusofurbanism.com') === -1 ?
            'target="_blank" class="external"' : ''
          return `<a ${ externalAttributes } href="${ url }">`
        }
      )
      // add wrapper to videos
      newMD = newMD.replace(/(<iframe.*<\/iframe>)/g, 
        (match, iframe) => `<div class="video-wrapper">${iframe}</div>`
      )
      return newMD
    },

    addHighlightForLinks () {
      if (!Array.isArray(this.mapPosition)) return
      this.$nextTick(() => {
        this.$refs.postcontent.querySelectorAll('a')
          .forEach(e => {
            const elText = e.innerHTML.toLowerCase().replace('&amp;', '&')
            const foundLocation = this.mapPosition.find(p => p.location && elText === p.location.toLowerCase())
            if (foundLocation){
              e.addEventListener('mouseover', () => this.doubleHighlight(foundLocation.location))
              e.addEventListener('mouseout', this.unDoubleHighlight)
            }
          })
      })
    },
  }
}
</script>

<style lang="scss" scoped>

h1 {
		margin-bottom: $unit * 2;
}

.japanese-available {
  background: $active;
  color: white;
  margin-bottom: $content-padding;
  text-align: center;

  @include width(mobile) {
    margin-bottom: $content-padding-mobile;
  }
}

.markdown {
  min-height: 50vh;
}

.details {
  @include width (mobile) {
    margin-top: 0;
  }
}

</style>
