<template>
  <section class="content" :class="{ja: displayLanguage === 'ja'}">

    <Lightbox />

    <Breadcrumb 
      :title="title"
    />

    <div 
      class="japanese-available content-top-full" 
      v-if="(userLanguage === 'ja' || isDev) && content.ja && content.en"
    >
      <template v-if="displayLanguage !== 'ja'">
        <img src="~/assets/icons/japanFlag.svg" class="flag-icon" />
        <span>日本語版もあります。</span>
        <span class="button invert" @click="setLanguage('ja')">切り替える</span>
      </template>
      <template v-else>
        <span>日本語版を表示しています。</span>
        <span class="button invert" @click="setLanguage('en')">英語に戻る</span>
      </template>
    </div>


    <h1>{{ title }}</h1>

    <PostDetails
      class="details"
      :category="category"
      :mapPosition="mapPosition"
      :city="city"
      :date="date"
    />

    <LoaderIcon
      v-if="loading"
      :active="loading"
      :absolute="false"
    />

    <article
      v-lazy-container="{
        selector: 'img[data-src]',
        preLoad: 1.5, // screen heights away to start loading
      }"
      class="markdown"
      ref="postcontent"
      v-html="contentToDisplay"
    ></article>

    <RelatedArticles :city="city" :current="slug" />

    <Footer/>

  </section>
</template>

<script>
import axios from 'axios'
import Footer from '~/components/Footer'
import PostDetails from '~/components/PostDetails'
import RelatedArticles from '~/components/RelatedArticles'
import Breadcrumb from '~/components/Breadcrumb'
import Lightbox from '~/components/Lightbox'
import LoaderIcon from '~/components/LoaderIcon'
const { capitalize } = require('~/assets/commonFunctions.js')

export default {
  head() {
    return {
      title: this.capitalize(this.title),
      meta: [
        { property: 'og:title', content: this.capitalize(this.title) },
        { hid: `og:type`, property: 'og:type', content: 'article' },
        { hid: `og:description`, property: 'og:description', content: this.description },
        { property: 'description', content: this.description, hid: `description` },
        { property: 'og:url', content: `https://www.travelingcircusofurbanism.com${ this.publicPath }` },
        { hid: `og:image`, property: 'og:image', content: 
          this.image ? // does it have an image?
            this.image.substring(0, 4) === 'http' ? // is it external?
              this.image : // if so, use it
              `https://www.travelingcircusofurbanism.com${ encodeURI(this.image) }` : // otherwise, give it a prefix
            'https://www.travelingcircusofurbanism.com/assets/sitethumbnail.jpg' // fallback to the site thumbnail.
         },
      ],
      // script: [
      //   { src: '/assets/pinit.js', defer: true, async: true, "data-pin-hover":"true", "data-pin-round":"true" }
      // ]
    }
  },
  
  components: { Footer, RelatedArticles, PostDetails, Breadcrumb, Lightbox, LoaderIcon },

  asyncData ({ route, redirect, error, env, store }) {
    const removeTrailingSlash = (string) => string.replace(/\/$/, '')
    const slug = removeTrailingSlash( decodeURI( route.path ) )

    const path = '/posts' + slug + '/'
    const publicPath = '/' + removeTrailingSlash(route.path) + '/'

    let city = route.path.substring(1)
    city = decodeURI(city.substring(0, city.indexOf('/'))).toLowerCase()

    const autoGeneratedData = store.state.allPosts
      .find(p => city === p.city && slug.indexOf(p.slug) !== -1)
    if (!autoGeneratedData) {
      // console.log('Error: Unable to find generated data for ' + path)
      return error({ statusCode: 404, message: 'Page not found.' })
    }

    return {
      path,
      publicPath,
      slug,
      city,
      ...autoGeneratedData,
      mapPosition: autoGeneratedData.mapPosition ? 
        Array.isArray(autoGeneratedData.mapPosition) ?
          autoGeneratedData.mapPosition
          : [autoGeneratedData.mapPosition]
        : [],
    }
  },

  data () {
    return {
      displayLanguage: 'en',
      loading: true,
      content: {
        en: null,
        ja: null
      }
    }
  },

  computed: {
    isDev () { return this.$store.state.isDev },
    isMobile () { return this.$store.state.isMobile },
    userLanguage () { return this.$store.state.language },
    publicPosts () { return this.$store.state.enPublicPosts },
    allPosts () { return this.$store.state.allPosts },
    contentInRightLanguage () {
      const contentInRightLanguage = this.content[this.displayLanguage] || this.content.en || this.content.ja || ''
      return contentInRightLanguage
    },
    contentToDisplay () {
      const contentToDisplay = this.highlightLocationText(this.contentInRightLanguage)
      this.$nextTick(this.addImageInteraction)
      this.$nextTick(this.addMapMoveOnHighlightTextHover)
      return contentToDisplay
    },
  },

  async created () {
    if (!process.browser) return
    const axiosConfig = {
      validateStatus: status => true,
    }
  
    const contentPromises = []
    if (this.languages.en)
      contentPromises.push(
        axios.get(this.path + 'generated/html/content.html', axiosConfig)
          .then(response => {
            this.$set(this.content, 'en', response.data)
          })
          .catch(e => console.log(e))
      )
    if (this.languages.ja)
      contentPromises.push(
        axios.get(this.path + 'generated/html/content.html', axiosConfig)
          .then(response => {
            this.$set(this.content, 'ja', response.data)
          })
          .catch(e => console.log(e))
      )
    await Promise.all(contentPromises)

    if (!(this.content.en || this.content.ja)) return this.$router.push('/')
    if (this.content.en) this.setLanguage('en')
    else this.setLanguage('ja')
    this.loading = false
  },

  mounted () {
    this.displayLanguage = this.content.en ? 'en' : 'ja'
    this.$store.commit('setView', this.mapPosition)
    this.$store.commit('setCity', this.city)
    this.$store.commit('setPan', false)
    this.$store.commit('setHighlight', this.mapPosition)
    this.$nextTick(() => {
      if (!this.public && !this.isDev)
        this.$store.commit('setMapMarkers', this.allPosts)
    })
  },

  beforeDestroy () {
    if (!this.public && !this.isDev)
      this.$store.commit('setMapMarkers', this.publicPosts)
    this.$store.commit('setHighlight')
  },

  methods: {
    capitalize,

    doubleHighlight (location) {
      this.$store.commit('setHighlight', location)
    },

    unDoubleHighlight () {
      this.$store.commit('setHighlight')
    },

    setLanguage (language) {
      this.displayLanguage = language
    },

    highlightLocationText () {
      if (!Array.isArray(this.mapPosition) || this.mapPosition.length === 1 || this.isMobile)
        return this.contentInRightLanguage
      let newContent = this.contentInRightLanguage
      this.mapPosition.map(positionObject => positionObject.location)
        .forEach(location => {
          if (location.length < 4) return
          const locationRegex = new RegExp(`[\s\n >]${location}`, 'gi')
          newContent = newContent.replace(locationRegex, match => 
            match.replace(location, `<span class="highlight">${location}</span>`)
          )
        })
      return newContent
    },

    addMapMoveOnHighlightTextHover () {
      if (!Array.isArray(this.mapPosition) || this.mapPosition.length === 1 || this.isMobile || !this.$refs || !this.$refs.postcontent) return
      this.$refs.postcontent.querySelectorAll('.highlight')
        .forEach(e => {
          const elText = e.innerHTML.toLowerCase().replace('&amp;', '&')
          const foundLocation = this.mapPosition.find(p => p.location && elText === p.location.toLowerCase())
          if (foundLocation) {
            e.addEventListener('mouseover', () => {
              this.doubleHighlight(foundLocation.location)
              this.$store.commit('setView', foundLocation)
            })
            e.addEventListener('mouseout', this.unDoubleHighlight)
          }
        })
    },

    addImageInteraction () {
      if (!this.$el) return
      this.$el.querySelectorAll('img')
        .forEach(e => {
          e.addEventListener('click', () => this.$store.commit('setLightboxSrc', e.getAttribute('data-src')))
        })
    }
  }
}
</script>

<style lang="scss" scoped>
@import '~/assets/variables.scss';

h1 {
		margin-bottom: $unit * 2;
}

.japanese-available {
  background: $active;
  color: white;
  margin-bottom: $content-padding;
  text-align: center;

  @include width(mobile) {
    margin-bottom: $content-padding-mobile;
  }
}

.markdown {
  min-height: 50vh;
}

.details {
  @include width (mobile) {
    margin-top: 0;
  }
}

</style>
