<template>
  <PostFullDisplay
    :prioritizeLanguage="'ja'"
    :key="'ja' + title"
    :title="title"
    :content="content"
    :category="category"
    :mapPosition="mapPosition"
    :city="city"
    :date="date"
    :loading="loading"
    :slug="slug"
    :description="description"
    :publicPath="publicPath"
    :path="path"
    :image="image"
    :jaTitle="jaTitle"
    :polygons="polygons"
    :public="public"
    :preview="preview"
  />
</template>

<script>
import axios from 'axios'
import PostFullDisplay from '~/components/PostFullDisplay'
const { capitalize } = require('~/assets/commonFunctions.js')

export default {
  scrollToTop: true,
  head() {
    return {
      title: this.capitalize(this.jaTitle),
      meta: [
        { property: 'og:title', content: this.capitalize(this.jaTitle) },
        { hid: `og:type`, property: 'og:type', content: 'article' },
        {
          hid: `og:description`,
          property: 'og:description',
          content: this.jaDescription || this.description,
        },
        {
          property: 'description',
          content: this.jaDescription || this.description,
          hid: `description`,
        },
        {
          property: 'og:url',
          content: `https://www.travelingcircusofurbanism.com${this.publicPath}`,
        },
        {
          hid: `og:image`,
          property: 'og:image',
          content: this.image // does it have an image?
            ? this.image.substring(0, 4) === 'http' // is it external?
              ? this.image // if so, use it
              : `https://www.travelingcircusofurbanism.com${encodeURI(
                  this.image
                )}` // otherwise, give it a prefix
            : 'https://www.travelingcircusofurbanism.com/assets/sitethumbnail.jpg', // and finally fallback to the site thumbnail.
        },
      ],
    }
  },

  components: {
    PostFullDisplay,
  },

  asyncData({ route, redirect, error, env, store }) {
    const removeTrailingSlash = string => string.replace(/\/$/, '')
    const slug = removeTrailingSlash(decodeURI(route.path))

    const path = '/posts' + slug.replace('/ja', '') + '/'
    const publicPath = slug + '/'

    let city = route.path.substring(1)
    city = decodeURI(city.substring(0, city.indexOf('/'))).toLowerCase()

    const autoGeneratedData = store.state.allPosts.find(
      p => city === p.city && slug.indexOf(p.slug) !== -1
    )
    if (!autoGeneratedData) {
      return error({ statusCode: 404, message: 'Page not found.' })
    }

    if (!autoGeneratedData.languages.ja)
      return redirect(route.path.replace('/ja', ''))

    return {
      path,
      publicPath,
      slug,
      city,
      preview: autoGeneratedData.preview,
      ...autoGeneratedData,
      mapPosition: autoGeneratedData.mapPosition
        ? Array.isArray(autoGeneratedData.mapPosition)
          ? autoGeneratedData.mapPosition
          : [autoGeneratedData.mapPosition]
        : [],
      polygons: autoGeneratedData.polygons ? autoGeneratedData.polygons : null,
    }
  },

  data() {
    return {
      loading: true,
      content: {
        en: null,
        ja: null,
      },
    }
  },

  async created() {
    // fetch the post content in both languages
    if (!process.browser) return

    const axiosConfig = {
      validateStatus: status => true,
    }

    const contentPromises = []

    try {
      if (this.languages.en)
        contentPromises.push(
          axios
            .get(this.path + 'content.html', axiosConfig)
            .then(response => {
              this.$set(this.content, 'en', response.data)
            })
            .catch(e => console.log(e))
        )
      if (this.languages.ja)
        contentPromises.push(
          axios
            .get(this.path + 'ja.html', axiosConfig)
            .then(response => {
              this.$set(this.content, 'ja', response.data)
            })
            .catch(e => console.log(e))
        )
      await Promise.all(contentPromises)
    } catch (e) {
      console.log(e)
      return this.$router.push('/')
    }

    if (!(this.content.en || this.content.ja)) return this.$router.push('/')
    this.loading = false
  },

  mounted() {},

  beforeDestroy() {},

  methods: {
    capitalize,
  },
}
</script>

<style lang="scss" scoped>
</style>
