<template>
  <PostFullDisplay
    :prioritizeLanguage="'en'"
    :key="'en' + title"
    :title="title"
    :content="content"
    :category="category"
    :mapPosition="mapPosition"
    :city="city"
    :date="date"
    :loading="loading"
    :slug="slug"
    :description="description"
    :publicPath="publicPath"
    :path="path"
    :image="image"
    :jaTitle="jaTitle"
    :polygons="polygons"
    :public="public"
    :preview="preview"
    :tags="tags"
  />
</template>

<script>
import axios from 'axios'
import PostFullDisplay from '~/components/PostFullDisplay'
const { capitalize } = require('~/assets/commonFunctions.js')

export default {
  scrollToTop: true,
  head() {
    return {
      title: this.capitalize(this.title),
      meta: [
        { property: 'og:title', content: this.capitalize(this.title) },
        { hid: `og:type`, property: 'og:type', content: 'article' },
        {
          hid: `og:description`,
          property: 'og:description',
          content: this.description,
        },
        {
          property: 'description',
          content: this.description,
          hid: `description`,
        },
        {
          property: 'og:url',
          content: `https://www.travelingcircusofurbanism.com${this.publicPath}`,
        },
        {
          hid: `og:image`,
          property: 'og:image',
          content: this.image // does it have an image?
            ? this.image.substring(0, 4) === 'http' // is it external?
              ? this.image // if so, use it
              : `https://www.travelingcircusofurbanism.com${encodeURI(
                  this.image
                )}` // otherwise, give it a prefix
            : 'https://www.travelingcircusofurbanism.com/assets/sitethumbnail.jpg', // fallback to the site thumbnail.
        },
      ],
    }
  },

  components: {
    PostFullDisplay,
  },

  async asyncData({ route, redirect, error, env, store }) {
    const removeTrailingSlash = string => string.replace(/\/$/, '')
    const slug = removeTrailingSlash(decodeURI(route.path))

    const path = '/posts' + slug + '/'
    const publicPath = slug + '/'

    let city = route.path.substring(1)
    city = decodeURI(city.substring(0, city.indexOf('/'))).toLowerCase()

    const autoGeneratedData = store.state.allPosts.find(
      p => city === p.city && slug.indexOf(p.slug) !== -1
    )
    if (!autoGeneratedData) {
      // console.log('Error: Unable to find generated data for ' + path)
      return error({ statusCode: 404, message: 'Page not found.' })
    }

    const content = {}
    if (process.server) {
      // can just get data with fs on server
      const fs = require('fs')
      try {
        content.en = fs.readFileSync('./nuxt/static' + path + 'en.html', 'utf8')
      } catch (e) {}
      try {
        content.ja = fs.readFileSync('./nuxt/static' + path + 'ja.html', 'utf8')
      } catch (e) {}
    } else {
      // have to use axios on the browser. yes, asyncData runs between pages on the browser. idk why.
      const axiosConfig = {
        validateStatus: status => true,
      }
      const contentPromises = []
      try {
        if (autoGeneratedData.languages.en)
          contentPromises.push(
            axios
              .get(path + 'en.html', axiosConfig)
              .then(response => (content.en = response.data))
              .catch(e => console.log(e))
          )
        if (autoGeneratedData.languages.ja)
          contentPromises.push(
            axios
              .get(path + 'ja.html', axiosConfig)
              .then(response => (content.ja = response.data))
              .catch(e => console.log(e))
          )
        await Promise.all(contentPromises)
      } catch (e) {
        console.log(e)
        return error({ statusCode: 404, message: 'Page not found.' })
      }
    }
    if (!(content.en || content.ja))
      return error({ statusCode: 404, message: 'Page not found.' })

    return {
      path,
      publicPath,
      slug,
      city,
      content,
      preview: autoGeneratedData.preview,
      jaTitle: autoGeneratedData.jaTitle,
      tags: [],
      ...autoGeneratedData,
      mapPosition: autoGeneratedData.mapPosition
        ? Array.isArray(autoGeneratedData.mapPosition)
          ? autoGeneratedData.mapPosition
          : [autoGeneratedData.mapPosition]
        : [],
      polygons: autoGeneratedData.polygons ? autoGeneratedData.polygons : null,
    }
  },

  data() {
    return {
      loading: false,
    }
  },

  methods: {
    capitalize,
  },
}
</script>

<style lang="scss" scoped>
</style>
